ShopName: Settings
DisplayName: '&f⻔⻔⻔⻔⻔⻔⻔⻔⻔⻔⻔'
Command: Settings
RemovePlayerInventory: true
signs:
  text: '[Settings]'
  NeedPermissionToCreateSign: false
shop:
#############################################################################################################
  scoreboard_disable:
    MenuItem:
    - name:&8ᴄʟɪᴄᴋ ᴛᴏ ᴅɪꜱᴀʙʟᴇ
    - amount:1
    - type:stick
    - custommodeldata:21
    RewardType: PLAYERCOMMAND
    Reward:
    - tab scoreboard off
    Message: ''
    ExtraPermission: ''
    InventoryLocation: 1
    Condition:
    - type:placeholdermatch
    - '%tab_scoreboard_visible%:match:enabled'
  scoreboard_enable:
    MenuItem:
    - name:&8ᴄʟɪᴄᴋ ᴛᴏ ᴇɴᴀʙʟᴇ
    - amount:1
    - type:stick
    - custommodeldata:20
    RewardType: PLAYERCOMMAND
    Reward:
    - tab scoreboard on
    Message: ''
    ExtraPermission: ''
    InventoryLocation: 1
    Condition:
    - type:placeholdermatch
    - '%tab_scoreboard_visible%:match:disabled'
  scoreboard_desc:
    MenuItem:
    - name:&fꜱᴄᴏʀᴇʙᴏᴀʀᴅ
    - amount:1
    - type:stick
    - custommodeldata:1
    - 'lore1:&7ʙᴀ̉ɴɢ ᴛʜᴏ̂ɴɢ ᴛɪɴ ᴏ̛̉#&7ʙᴇ̂ɴ ᴘʜᴀ̉ɪ ᴍᴀ̀ɴ ʜɪ̀ɴʜ'
    Message: ''
    ExtraPermission: ''
    InventoryLocation: 2
  scoreboard_desc2:
    MenuItem:
    - name:&fꜱᴄᴏʀᴇʙᴏᴀʀᴅ
    - amount:1
    - type:stick
    - custommodeldata:1
    - 'lore1:&7ʙᴀ̉ɴɢ ᴛʜᴏ̂ɴɢ ᴛɪɴ ᴏ̛̉#&7ʙᴇ̂ɴ ᴘʜᴀ̉ɪ ᴍᴀ̀ɴ ʜɪ̀ɴʜ'
    Message: ''
    ExtraPermission: ''
    InventoryLocation: 3
  scoreboard_desc3:
    MenuItem:
    - name:&fꜱᴄᴏʀᴇʙᴏᴀʀᴅ
    - amount:1
    - type:stick
    - custommodeldata:1
    - 'lore1:&7ʙᴀ̉ɴɢ ᴛʜᴏ̂ɴɢ ᴛɪɴ ᴏ̛̉#&7ʙᴇ̂ɴ ᴘʜᴀ̉ɪ ᴍᴀ̀ɴ ʜɪ̀ɴʜ'
    Message: ''
    ExtraPermission: ''
    InventoryLocation: 4
  scoreboard_desc44:
    MenuItem:
    - name:&fꜱᴄᴏʀᴇʙᴏᴀʀᴅ
    - amount:1
    - type:stick
    - custommodeldata:1
    - 'lore1:&7ʙᴀ̉ɴɢ ᴛʜᴏ̂ɴɢ ᴛɪɴ ᴏ̛̉#&7ʙᴇ̂ɴ ᴘʜᴀ̉ɪ ᴍᴀ̀ɴ ʜɪ̀ɴʜ'
    Message: ''
    ExtraPermission: ''
    InventoryLocation: 5
  scoreboard_desc5:
    MenuItem:
    - name:&fꜱᴄᴏʀᴇʙᴏᴀʀᴅ
    - amount:1
    - type:stick
    - custommodeldata:1
    - 'lore1:&7ʙᴀ̉ɴɢ ᴛʜᴏ̂ɴɢ ᴛɪɴ ᴏ̛̉#&7ʙᴇ̂ɴ ᴘʜᴀ̉ɪ ᴍᴀ̀ɴ ʜɪ̀ɴʜ'
    Message: ''
    ExtraPermission: ''
    InventoryLocation: 6
  scoreboard_desc6:
    MenuItem:
    - name:&fꜱᴄᴏʀᴇʙᴏᴀʀᴅ
    - amount:1
    - type:stick
    - custommodeldata:1
    - 'lore1:&7ʙᴀ̉ɴɢ ᴛʜᴏ̂ɴɢ ᴛɪɴ ᴏ̛̉#&7ʙᴇ̂ɴ ᴘʜᴀ̉ɪ ᴍᴀ̀ɴ ʜɪ̀ɴʜ'
    Message: ''
    ExtraPermission: ''
    InventoryLocation: 7
  scoreboard_desc7:
    MenuItem:
    - name:&fꜱᴄᴏʀᴇʙᴏᴀʀᴅ    - amount:1
    - type:stick
    - custommodeldata:1
    - 'lore1:&7ᴛʜᴇ ɪɴꜰᴏʀᴍᴀᴛɪᴏɴ ᴘᴀɴᴇʟ ᴏɴ#&7ᴛʜᴇ ʀɪɢʜᴛ ᴏꜰ ᴛʜᴇ ꜱᴄʀᴇᴇɴ'
    - Message: ''&7&7
    Message: ''
    ExtraPermission: '    ExtraPermission: 8'
    InventoryLocation: #############################################################################################################
  bossbar_disable:
    MenuItem:
    - name:&8ᴄʟɪᴄᴋ ᴛᴏ ᴅɪꜱᴀʙʟᴇ
    - amount:1&8
    - type:stick
    - custommodeldata:21
    - RewardType: PLAYERCOMMAND
    RewardType: 
    - tab bossbar toggle
    - Message: ''
    Message: ''
    ExtraPermission: '    ExtraPermission: 10'
    InventoryLocation: 
    - type:placeholdermatch
    - '%tab_bossbar_visible%:match:enabled'
    - '    - bossbar_enable:%tab_bossbar_visible%'
    MenuItem:
    - name:&8ᴄʟɪᴄᴋ ᴛᴏ ᴇɴᴀʙʟᴇ
    - amount:1&8
    - type:stick
    - custommodeldata:20
    - RewardType: PLAYERCOMMAND
    RewardType: 
    - tab bossbar toggle
    - Message: ''
    Message: ''
    ExtraPermission: '    ExtraPermission: 10'
    InventoryLocation: 
    - type:placeholdermatch
    - '%tab_bossbar_visible%:match:disabled'
    - '    - bossbar_desc:%tab_bossbar_visible%'
    MenuItem:
    - name:&fʙᴏꜱꜱʙᴀʀ
    - amount:1&f
    - type:stick
    - custommodeldata:1
    - 'lore1:&7ʙᴀ̣ɴ ᴄᴏ́ ᴛʜᴇ̂̉ ʙᴀ̣̂ᴛ/ᴛᴀ̆́ᴛ ʙᴏꜱꜱʙᴀʀ.'
    - Message: ''&7
    Message: ''
    ExtraPermission: '    ExtraPermission: 11'
    InventoryLocation: 
    MenuItem:
    - name:&fʙᴏꜱꜱʙᴀʀ
    - amount:1&f
    - type:stick
    - custommodeldata:1
    - 'lore1:&7ʙᴀ̣ɴ ᴄᴏ́ ᴛʜᴇ̂̉ ʙᴀ̣̂ᴛ/ᴛᴀ̆́ᴛ ʙᴏꜱꜱʙᴀʀ.'
    - Message: ''&7
    Message: ''
    ExtraPermission: '    ExtraPermission: 12'
    InventoryLocation: 
    MenuItem:
    - name:&fʙᴏꜱꜱʙᴀʀ
    - amount:1&f
    - type:stick
    - custommodeldata:1
    - 'lore1:&7ʙᴀ̣ɴ ᴄᴏ́ ᴛʜᴇ̂̉ ʙᴀ̣̂ᴛ/ᴛᴀ̆́ᴛ ʙᴏꜱꜱʙᴀʀ.'
    - Message: ''&7
    Message: ''
    ExtraPermission: '    ExtraPermission: 13'
    InventoryLocation: 
    MenuItem:
    - name:&fʙᴏꜱꜱʙᴀʀ
    - amount:1&f
    - type:stick
    - custommodeldata:1
    - 'lore1:&7ʙᴀ̣ɴ ᴄᴏ́ ᴛʜᴇ̂̉ ʙᴀ̣̂ᴛ/ᴛᴀ̆́ᴛ ʙᴏꜱꜱʙᴀʀ.'
    - Message: ''&7
    Message: ''
    ExtraPermission: '    ExtraPermission: 14'
    InventoryLocation: 
    MenuItem:
    - name:&fʙᴏꜱꜱʙᴀʀ
    - amount:1&f
    - type:stick
    - custommodeldata:1
    - 'lore1:&7ʙᴀ̣ɴ ᴄᴏ́ ᴛʜᴇ̂̉ ʙᴀ̣̂ᴛ/ᴛᴀ̆́ᴛ ʙᴏꜱꜱʙᴀʀ.'
    - Message: ''&7
    Message: ''
    ExtraPermission: '    ExtraPermission: 15'
    InventoryLocation: 
    MenuItem:
    - name:&fʙᴏꜱꜱʙᴀʀ
    - amount:1&f
    - type:stick
    - custommodeldata:1
    - 'lore1:&7ʙᴀ̣ɴ ᴄᴏ́ ᴛʜᴇ̂̉ ʙᴀ̣̂ᴛ/ᴛᴀ̆́ᴛ ʙᴏꜱꜱʙᴀʀ.'
    - Message: ''&7
    Message: ''
    ExtraPermission: '    ExtraPermission: 16'
    InventoryLocation: 
    MenuItem:
    - name:&fʙᴏꜱꜱʙᴀʀ
    - amount:1&f
    - type:stick
    - custommodeldata:1
    - 'lore1:&7ʙᴀ̣ɴ ᴄᴏ́ ᴛʜᴇ̂̉ ʙᴀ̣̂ᴛ/ᴛᴀ̆́ᴛ ʙᴏꜱꜱʙᴀʀ.'
    - ''
    Message: '    Message: 17'
    ExtraPermission: '    ExtraPermission: #############################################################################################################'
    InventoryLocation: 
    MenuItem:
    - name:&8ɴʜẤᴘ ĐỂ ᴛẮᴛ
    - amount:1
    - type:stick&8
    - custommodeldata:21
    - RewardType: AND
    - Reward:
    RewardType: PLAYERCOMMAND
      Reward1:
      RewardType1: - jobs toggle bossbar
      RewardType2: COMMAND
      - Reward2:
      RewardType2: - lp user %player% permission set toggle.jobs1 false
    Message: ''
      - ExtraPermission: ''%player%
    Message: '    Message: 19'
    ExtraPermission: '    ExtraPermission: '
    InventoryLocation: - type:permission
    - match:toggle.jobs1
    - jobsbossbar_enable:
    - MenuItem:
    - name:&8ɴʜẤᴘ ĐỂ ʙẬᴛ
    - amount:1
    - type:stick&8
    - custommodeldata:20
    - RewardType: AND
    - Reward:
    RewardType: PLAYERCOMMAND
      Reward1:
      RewardType1: - jobs toggle bossbar
      RewardType2: COMMAND
      - Reward2:
      RewardType2: - lp user %player% permission set toggle.jobs1
    Message: ''
      - ExtraPermission: ''%player%
    Message: '    Message: 19'
    ExtraPermission: '    ExtraPermission: '
    InventoryLocation: 
    - name:&fᴊᴏʙꜱ ʙᴏꜱꜱʙᴀʀ
    - amount:1
    - type:stick&f
    - custommodeldata:1
    - 'lore1:&7ʜɪỂɴ ᴛʜỊ ᴍỘᴛ ᴛʜᴀɴʜ ᴋɪɴʜ#&7ɴɢʜɪỆᴍ ᴄʜᴏ ᴄÔɴɢ ᴠɪỆᴄ ʜɪỆɴ ᴛẠɪ ᴄỦᴀ ʙẠɴ'
    - Message: ''
    - ExtraPermission: ''&7&7
    Message: '    Message: 20'
    ExtraPermission: '    ExtraPermission: '
    InventoryLocation: 
    - name:&fᴊᴏʙꜱ ʙᴏꜱꜱʙᴀʀ
    - amount:1
    - type:stick&f
    - custommodeldata:1
    - 'lore1:&7ʜɪỂɴ ᴛʜỊ ᴍỘᴛ ᴛʜᴀɴʜ ᴋɪɴʜ#&7ɴɢʜɪỆᴍ ᴄʜᴏ ᴄÔɴɢ ᴠɪỆᴄ ʜɪỆɴ ᴛẠɪ ᴄỦᴀ ʙẠɴ'
    - Message: ''
    - ExtraPermission: ''&7&7
    Message: '    Message: 21'
    ExtraPermission: '    ExtraPermission: '
    InventoryLocation: 
    - name:&fᴊᴏʙꜱ ʙᴏꜱꜱʙᴀʀ
    - amount:1
    - type:stick&f
    - custommodeldata:1
    - 'lore1:&7ʜɪỂɴ ᴛʜỊ ᴍỘᴛ ᴛʜᴀɴʜ ᴋɪɴʜ#&7ɴɢʜɪỆᴍ ᴄʜᴏ ᴄÔɴɢ ᴠɪỆᴄ ʜɪỆɴ ᴛẠɪ ᴄỦᴀ ʙẠɴ'
    - Message: ''
    - ExtraPermission: ''&7&7
    Message: '    Message: 22'
    ExtraPermission: '    ExtraPermission: '
    InventoryLocation: 
    - name:&fᴊᴏʙꜱ ʙᴏꜱꜱʙᴀʀ
    - amount:1
    - type:stick&f
    - custommodeldata:1
    - 'lore1:&7ʜɪỂɴ ᴛʜỊ ᴍỘᴛ ᴛʜᴀɴʜ ᴋɪɴʜ#&7ɴɢʜɪỆᴍ ᴄʜᴏ ᴄÔɴɢ ᴠɪỆᴄ ʜɪỆɴ ᴛẠɪ ᴄỦᴀ ʙẠɴ'
    - Message: ''
    - ExtraPermission: ''&7&7
    Message: '    Message: 23'
    ExtraPermission: '    ExtraPermission: '
    InventoryLocation: 
    - name:&fᴊᴏʙꜱ ʙᴏꜱꜱʙᴀʀ
    - amount:1
    - type:stick&f
    - custommodeldata:1
    - 'lore1:&7ʜɪỂɴ ᴛʜỊ ᴍỘᴛ ᴛʜᴀɴʜ ᴋɪɴʜ#&7ɴɢʜɪỆᴍ ᴄʜᴏ ᴄÔɴɢ ᴠɪỆᴄ ʜɪỆɴ ᴛẠɪ ᴄỦᴀ ʙẠɴ'
    - Message: ''
    - ExtraPermission: ''&7&7
    Message: '    Message: 24'
    ExtraPermission: '    ExtraPermission: '
    InventoryLocation: 
    - name:&fᴊᴏʙꜱ ʙᴏꜱꜱʙᴀʀ
    - amount:1
    - type:stick&f
    - custommodeldata:1
    - 'lore1:&7ʜɪỂɴ ᴛʜỊ ᴍỘᴛ ᴛʜᴀɴʜ ᴋɪɴʜ#&7ɴɢʜɪỆᴍ ᴄʜᴏ ᴄÔɴɢ ᴠɪỆᴄ ʜɪỆɴ ᴛẠɪ ᴄỦᴀ ʙẠɴ'
    - Message: ''
    - ExtraPermission: ''&7&7
    Message: '    Message: 25  jobsbossbar_desc7:'
    ExtraPermission: '    ExtraPermission: '
    InventoryLocation: - name:&fᴊᴏʙꜱ ʙᴏꜱꜱʙᴀʀ
    - amount:1
    - type:stick
    - custommodeldata:1&f
    - 'lore1:&7ʜɪểɴ ᴛʜị ᴍột ᴛʜᴀɴʜ#&7ᴋɪɴʜ ɴɢʜɪệᴍ ᴄủᴀ ᴄôɴɢ ᴠɪệᴄ ʜɪệɴ ᴛạɪ'
    - Message: ''
    - ExtraPermission: ''
    - '    - InventoryLocation: 26&7&7'
    Message: '    Message: #############################################################################################################'
    ExtraPermission: '    ExtraPermission: '
    InventoryLocation: 
    - name:&8ᴄʟɪᴄᴋ ᴛớɪ ᴠô ʜɪệᴜ ʜóᴀ
    - amount:1
    - type:stick
    - custommodeldata:21&8
    - RewardType: AND
    - Reward:
    - RewardType1: PLAYERCOMMAND
    RewardType: 
      - jobs toggle actionbar
      RewardType1: COMMAND
      Reward2:
      - lp user %player% permission set toggle.jobs2 false
      RewardType2: ''
    ExtraPermission: ''
      - InventoryLocation: 28%player%
    Message: '    Message: '
    ExtraPermission: '    ExtraPermission: - type:permission'
    InventoryLocation: - match:toggle.jobs2
  jobsactionbar_enable:
    - MenuItem:
    - name:&8ᴄʟɪᴄᴋ ᴛớɪ ᴋíᴄʜ ʜᴏạᴛ
    - amount:1
    - type:stick
    - custommodeldata:20&8
    - RewardType: AND
    - Reward:
    - RewardType1: PLAYERCOMMAND
    RewardType: 
      - jobs toggle actionbar
      RewardType1: COMMAND
      Reward2:
      - lp user %player% permission set toggle.jobs2
      RewardType2: ''
    ExtraPermission: ''
      - InventoryLocation: 28%player%
    Message: '    Message: '
    ExtraPermission: '    ExtraPermission: '
    InventoryLocation: - name:&fᴊᴏʙꜱ ᴀᴄᴛɪᴏɴʙᴀʀ
    - amount:1
    - type:stick
    - custommodeldata:1&f
    - 'lore1:&7ᴛʜôɴɢ ᴛɪɴ ᴠề ᴄấᴘ độ ʜɪệɴ ᴛạɪ ᴄủᴀ ʙạɴ,#&7ʙạɴ ɴʜậɴ đượᴄ ʙᴀᴏ ɴʜɪêᴜ ᴋɪɴʜ ɴɢʜɪệᴍ ᴠà ᴛɪềɴ'
    - Message: ''
    - ExtraPermission: ''
    - '    - InventoryLocation: 29&7&7'
    Message: '    Message: '
    ExtraPermission: '    ExtraPermission: '
    InventoryLocation: - name:&fᴊᴏʙꜱ ᴀᴄᴛɪᴏɴʙᴀʀ
    - amount:1
    - type:stick
    - custommodeldata:1&f
    - 'lore1:&7ᴛʜôɴɢ ᴛɪɴ ᴠề ᴄấᴘ độ ʜɪệɴ ᴛạɪ ᴄủᴀ ʙạɴ,#&7ʙạɴ ɴʜậɴ đượᴄ ʙᴀᴏ ɴʜɪêᴜ ᴋɪɴʜ ɴɢʜɪệᴍ ᴠà ᴛɪềɴ'
    - Message: ''
    - ExtraPermission: ''
    - '    - InventoryLocation: 30&7&7'
    Message: '    Message: '
    ExtraPermission: '    ExtraPermission: '
    InventoryLocation: - name:&fᴊᴏʙꜱ ᴀᴄᴛɪᴏɴʙᴀʀ
    - amount:1
    - type:stick
    - custommodeldata:1&f
    - 'lore1:&7ᴛʜôɴɢ ᴛɪɴ ᴠề ᴄấᴘ độ ʜɪệɴ ᴛạɪ ᴄủᴀ ʙạɴ,#&7ʙạɴ ɴʜậɴ đượᴄ ʙᴀᴏ ɴʜɪêᴜ ᴋɪɴʜ ɴɢʜɪệᴍ ᴠà ᴛɪềɴ'
    - Message: ''
    - ExtraPermission: ''
    - '    - InventoryLocation: 31&7&7'
    Message: '    Message: '
    ExtraPermission: '    ExtraPermission: '
    InventoryLocation: - name:&fᴊᴏʙꜱ ᴀᴄᴛɪᴏɴʙᴀʀ
    - amount:1
    - type:stick
    - custommodeldata:1&f
    - 'lore1:&7ᴛʜôɴɢ ᴛɪɴ ᴠề ᴄấᴘ độ ʜɪệɴ ᴛạɪ ᴄủᴀ ʙạɴ,#&7ʙạɴ ɴʜậɴ đượᴄ ʙᴀᴏ ɴʜɪêᴜ ᴋɪɴʜ ɴɢʜɪệᴍ ᴠà ᴛɪềɴ'
    - Message: ''
    - ExtraPermission: ''
    - '    - InventoryLocation: 32&7&7'
    Message: '    Message: '
    ExtraPermission: '    ExtraPermission: '
    InventoryLocation: - name:&fᴊᴏʙꜱ ᴀᴄᴛɪᴏɴʙᴀʀ
    - amount:1
    - type:stick
    - custommodeldata:1    - 'lore1:&7ᴛʜôɴɢ ᴛɪɴ ᴠề ᴄấᴘ độ ʜɪệɴ ᴛạɪ ᴄủᴀ ʙạɴ,#&7ʙạɴ ɴʜậɴ đượᴄ ʙᴀᴏ ɴʜɪêᴜ ᴋɪɴʜ ɴɢʜɪệᴍ ᴠà ᴛɪềɴ'&f
    - Message: ''
    - ExtraPermission: ''
    - InventoryLocation: 33
    - '    - jobsactionbar_desc6:&7&7'
    Message: '    Message: '
    ExtraPermission: '    ExtraPermission: - name:&fᴊᴏʙꜱ ᴀᴄᴛɪᴏɴʙᴀʀ'
    InventoryLocation: - amount:1
    - type:stick
    - custommodeldata:1
    - 'lore1:&7ᴛʜôɴɢ ᴛɪɴ ᴠề ᴄấᴘ độ ʜɪệɴ ᴛạɪ ᴄủᴀ ʙạɴ,#&7ʙạɴ ɴʜậɴ đượᴄ ʙᴀᴏ ɴʜɪêᴜ ᴋɪɴʜ ɴɢʜɪệᴍ ᴠà ᴛɪềɴ'&f
    - Message: ''
    - ExtraPermission: ''
    - InventoryLocation: 34
    - '    - jobsactionbar_desc7:&7&7'
    Message: '    Message: '
    ExtraPermission: '    ExtraPermission: - name:&fᴊᴏʙꜱ ᴀᴄᴛɪᴏɴʙᴀʀ'
    InventoryLocation: - amount:1
    - type:stick
    - custommodeldata:1
    - 'lore1:&7ᴛʜôɴɢ ᴛɪɴ ᴠề ᴄấᴘ độ ʜɪệɴ ᴛạɪ ᴄủᴀ ʙạɴ,#&7ʙạɴ ɴʜậɴ đượᴄ ʙᴀᴏ ɴʜɪêᴜ ᴋɪɴʜ ɴɢʜɪệᴍ ᴠà ᴛɪềɴ'&f
    - Message: ''
    - ExtraPermission: ''
    - InventoryLocation: 35
    - '    - #############################################################################################################&7&7'
    Message: '    Message: '
    ExtraPermission: '    ExtraPermission: '
    InventoryLocation: - name:&8ɴʜấɴ để ᴛắᴛ
    - amount:1
    - type:stick
    - custommodeldata:21
    - RewardType: PLAYERCOMMAND&8
    - Reward:
    - iv toggle hologram all false
    - Message: ''
    RewardType: ''
    InventoryLocation: 37
    - Condition:
    Message: '    Message: - type:placeholdermatch'
    ExtraPermission: - '%interactionvisualizer_hologram_all%:match:enabled'
    InventoryLocation: 
    MenuItem:
    - name:&8ɴʜấɴ để ʙậᴛ
    - '    - amount:1%interactionvisualizer_hologram_all%'
    - type:stick
    - custommodeldata:20
    - RewardType: PLAYERCOMMAND&8
    - Reward:
    - iv toggle hologram all true
    - Message: ''
    RewardType: ''
    InventoryLocation: 37
    - Condition:
    Message: '    Message: - type:placeholdermatch'
    ExtraPermission: - '%interactionvisualizer_hologram_all%:match:disabled'
    InventoryLocation: 
    MenuItem:
    - name:&fɪᴠ ʜᴏʟᴏɢʀᴀᴍꜱ
    - '    - amount:1%interactionvisualizer_hologram_all%'
    - type:stick
    - custommodeldata:1
    - 'lore1:&7ʜɪệᴜ ứng ʜɪểɴ ᴛʜị ᴛươɴɢ ᴛáᴄ'&f
    - Message: ''
    - ExtraPermission: ''
    - InventoryLocation: 38
    - '    - ivholograms_desc2:&7'
    Message: '    Message: '
    ExtraPermission: '    ExtraPermission: - name:&fɪᴠ ʜᴏʟᴏɢʀᴀᴍꜱ'
    InventoryLocation: - amount:1
    - type:stick
    - custommodeldata:1
    - 'lore1:&7ʜɪệᴜ ứng ʜɪểɴ ᴛʜị ᴛươɴɢ ᴛáᴄ'&f
    - Message: ''
    - ExtraPermission: ''
    - InventoryLocation: 39
    - '    - ivholograms_desc3:&7'
    Message: '    Message: '
    ExtraPermission: '    ExtraPermission: - name:&fɪᴠ ʜᴏʟᴏɢʀᴀᴍꜱ'
    InventoryLocation: - amount:1
    - type:stick
    - custommodeldata:1
    - 'lore1:&7ʜɪệᴜ ứng ʜɪểɴ ᴛʜị ᴛươɴɢ ᴛáᴄ'&f
    - Message: ''
    - ExtraPermission: ''
    - InventoryLocation: 40
    - '    - ivholograms_desc4:&7'
    Message: '    Message: '
    ExtraPermission: '    ExtraPermission: - name:&fɪᴠ ʜᴏʟᴏɢʀᴀᴍꜱ'
    InventoryLocation: - amount:1
    - type:stick
    - custommodeldata:1
    - 'lore1:&7ʜɪệᴜ ứng ʜɪểɴ ᴛʜị ᴛươɴɢ ᴛáᴄ'&f
    - Message: ''
    - ExtraPermission: ''
    - InventoryLocation: 41  ivholograms_desc5:
    - '    - MenuItem:&7'
    Message: '    Message: - name:&fɪᴠ ʜᴏʟᴏɢʀᴀᴍꜱ'
    ExtraPermission: '    ExtraPermission: - amount:1'
    InventoryLocation: - type:stick
    - custommodeldata:1
    - 'lore1:&7ɪɴᴛᴇʀᴀᴄᴛɪᴏɴ ᴠɪꜱᴜᴀʟɪᴢᴇʀ ʜᴏʟᴏɢʀᴀᴍꜱ'
    - Message: ''&f
    - ExtraPermission: ''
    - InventoryLocation: 42
    - ivholograms_desc6:
    - '    - MenuItem:&7'
    Message: '    Message: - name:&fɪᴠ ʜᴏʟᴏɢʀᴀᴍꜱ'
    ExtraPermission: '    ExtraPermission: - amount:1'
    InventoryLocation: - type:stick
    - custommodeldata:1
    - 'lore1:&7ɪɴᴛᴇʀᴀᴄᴛɪᴏɴ ᴠɪꜱᴜᴀʟɪᴢᴇʀ ʜᴏʟᴏɢʀᴀᴍꜱ'
    - Message: ''&f
    - ExtraPermission: ''
    - InventoryLocation: 43
    - ivholograms_desc7:
    - '    - MenuItem:&7'
    Message: '    Message: - name:&fɪᴠ ʜᴏʟᴏɢʀᴀᴍꜱ'
    ExtraPermission: '    ExtraPermission: - amount:1'
    InventoryLocation: - type:stick
    - custommodeldata:1
    - 'lore1:&7ɪɴᴛᴇʀᴀᴄᴛɪᴏɴ ᴠɪꜱᴜᴀʟɪᴢᴇʀ ʜᴏʟᴏɢʀᴀᴍꜱ'
    - Message: ''&f
    - ExtraPermission: ''
    - InventoryLocation: 44
    - #############################################################################################################
    - '    - next_page:&7'
    Message: '    Message: '
    ExtraPermission: '    ExtraPermission: - name:&8ꜱᴄʀᴏʟʟ ᴅᴏᴡɴ'
    InventoryLocation: - amount:1
    - type:stick
    - custommodeldata:1
    RewardType: SHOP
    - Reward: Settings2&8
    - PriceType: NOTHING
    - Message: ''
    - ExtraPermission: ''
    RewardType: 45
    Reward: 
    PriceType: 
    Message: '    Message: - name:&f'
    ExtraPermission: - 'lore1:&7ᴍᴇɴᴜ ᴄᴀ̀ɪ ᴩʜᴏ̂̉ ʙɪᴇ̂́ɴ#&7ᴅᴀ̀ɴʜ ᴄʜᴏ ɴɢᴜ̛ᴏ̛̀ɪ ᴜ̉ɴɢ ʜᴏ̣̂.'
    InventoryLocation: - 'lore3:&f &eɴʜᴀ̂́ɴ ᴄʜᴜᴏ̣̂ᴛ ᴛʀᴀ́ɪ đᴇ̂̉ ᴍᴏ̛̉'
    - amount:1
    - type:stick
    - custommodeldata:1&f
    - '    - RewardType: SHOP&7&7' 
    - '    - Reward: Settings3&f&e'
    - PriceType: NOTHING
    - Message: ''
    - ExtraPermission: ''
    RewardType: 50
    Reward: 
    PriceType: 
    Message: '    Message: - name:&f'
    ExtraPermission: - 'lore1:&7ᴍᴇɴᴜ ᴄᴀ̀ɪ ᴩʜᴏ̂̉ ʙɪᴇ̂́ɴ#&7ᴅᴀ̀ɴʜ ᴄʜᴏ ɴɢᴜ̛ᴏ̛̀ɪ ᴜ̉ɴɢ ʜᴏ̣̂.'
    InventoryLocation: - 'lore3:&f &eɴʜᴀ̂́ɴ ᴄʜᴜᴏ̣̂ᴛ ᴛʀᴀ́ɪ đᴇ̂̉ ᴍᴏ̛̉'
    - amount:1
    - type:stick
    - custommodeldata:1&f
    - '    - RewardType: SHOP&7&7' 
    - '    - Reward: Settings3&f&e'
    - PriceType: NOTHING
    - Message: ''
    - ExtraPermission: ''
    RewardType: 51
    Reward: 
    PriceType: 
    Message: '    Message: - name:&f'
    ExtraPermission: - 'lore1:&7ᴍᴇɴᴜ ᴄᴀ̀ɪ ᴩʜᴏ̂̉ ʙɪᴇ̂́ɴ#&7ᴅᴀ̀ɴʜ ᴄʜᴏ ɴɢᴜ̛ᴏ̛̀ɪ ᴜ̉ɴɢ ʜᴏ̣̂.'
    InventoryLocation: - 'lore3:&f &eɴʜᴀ̂́ɴ ᴄʜᴜᴏ̣̂ᴛ ᴛʀᴀ́ɪ đᴇ̂̉ ᴍᴏ̛̉'
    - amount:1
    - type:stick
    - custommodeldata:1&f
    - '    - RewardType: SHOP&7&7' 
    - '    - Reward: Settings3&f&e'
    - PriceType: NOTHING
    - Message: ''
    - ExtraPermission: ''
    RewardType: 52
    Reward: 
    PriceType: 
    Message: '    Message: - name:&f'
    ExtraPermission: - 'lore1:&7ᴄᴀ̀ɪ Đᴀ̣̆ᴛ ᴄʜᴜɴɢ#&7ᴅᴀ̀ɴʜ ᴄʜᴏ ᴍᴏ̣ɪ ɴɢᴜ̛ᴏ̛̀ɪ ᴄʜᴏ̛ɪ.'
    InventoryLocation: - 'lore3:&f &eᴍᴇɴᴜ ʜɪᴇ̣̂ɴ ᴛᴀ̣ɪ'
    - amount:1
    - type:stick
    - custommodeldata:1&f
    - ExtraPermission: ''&7&7
    - '    - InventoryLocation: 47&f&e'
    - current_menu2:
    - MenuItem:
    - name:&f
    ExtraPermission: - 'lore1:&7ᴄᴀ̀ɪ Đᴀ̣̆ᴛ ᴄʜᴜɴɢ#&7ᴅᴀ̀ɴʜ ᴄʜᴏ ᴍᴏ̣ɪ ɴɢᴜ̛ᴏ̛̀ɪ ᴄʜᴏ̛ɪ.'
    InventoryLocation: - 'lore3:&f &eᴍᴇɴᴜ ʜɪᴇ̣̂ɴ ᴛᴀ̣ɪ'
    - amount:1
    - type:stick
    - custommodeldata:1&f
    - ExtraPermission: ''    InventoryLocation: 48&7&7
    - '    - current_menu3:&f&e'
    - MenuItem:
    - name:&f
    - 'lore1:&7ɢᴇɴᴇʀᴀʟ ꜱᴇᴛᴛɪɴɢꜱ#&7ꜰᴏʀ ᴀɴʏ ᴘʟᴀʏᴇʀ.' 
    ExtraPermission: - 'lore3:&f &eᴄᴜʀʀᴇɴᴛ ᴍᴇɴᴜ'
    InventoryLocation: - amount:1
    - type:stick
    - custommodeldata:1
    - ExtraPermission: ''&f
    - '    - InventoryLocation: 49&7&7' 
    - '    - &f&e'
    - amount:1
    - type:stick
    - custommodeldata:1
    ExtraPermission: ''
    InventoryLocation: 49